apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP_NAME}-env
data:
  APP_VERSION: ${APP_VERSION}
  REDIS_HOST: "clustercfg.alboomgeneral.bvzhav.use1.cache.amazonaws.com"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_CLUSTER_MODE: "true"
  REDIS_TLS_ENABLED: "true"

