apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}
  labels:
    app: ${APP_NAME}
spec:
  type: ClusterIP
  ports:
  - port: ${APP_PORT}
    targetPort: ${APP_PORT}
    protocol: TCP
    name: http
  - port: 4433
    targetPort: 4433
    protocol: TCP
    name: https
  selector:
    app: ${APP_NAME}

